GET http://localhost:8000/api/student
x-api-version: '2023-19-05'

###
POST http://localhost:8000/api/students
Content-Type: application/json

{
    "username": "trung handsome",
    "password": "easy"
}