version: "3"
services:
  rmq:
    build:
      context: ./rmq
    ports:
      - 5672:5672
      - 15672:15672
  # nestjs-microservice:
  #   build:
  #     context: ./nestjs-microservice
  #   ports:
  #     - 1111:1111
  #   depends_on:
  #     - rmq
  #   env_file:
  #     - .env/.nestjs-microservice.env

  # nestjs-microservice-2:
  #   build:
  #     context: ./nestjs-microservice-2
  #   ports:
  #     - 2222:2222
  #   depends_on:
  #     - rmq
  #   env_file:
  #     - .env/.nestjs-microservice-2.env

  # kong:
  #   build:
  #     context: ./kong
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #     - 8443:8443
  #   depends_on:
  #     - nestjs-microservice
  #     - nestjs-microservice-2
